# Generated by Django 6.0.6 on 2026-06-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('cv', 'CV'), ('resume', 'Resume'), ('cover_letter', 'Cover Letter')], default='resume', max_length=20)),
                ('template', models.CharField(choices=[('modern_pro', 'Modern Professional'), ('minimal_pure', 'Minimal Pure'), ('creative_burst', 'Creative Burst'), ('executive_elite', 'Executive Elite'), ('tech_nexus', 'Tech Nexus'), ('academic_scholar', 'Academic Scholar'), ('gradient_flow', 'Gradient Flow'), ('sidebar_pro', 'Sidebar Pro'), ('compact_card', 'Compact Card'), ('bold_statement', 'Bold Statement')], default='modern_pro', max_length=30)),
                ('content', models.JSONField(default=dict)),
                ('section_order', models.JSONField(default=list)),
                ('primary_color', models.CharField(default='#2563eb', max_length=7)),
                ('font_family', models.CharField(default='Inter', max_length=50)),
                ('ai_score', models.FloatField(blank=True, null=True)),
                ('ai_feedback', models.JSONField(blank=True, default=list)),
                ('last_analyzed', models.DateTimeField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, upload_to='resumes/%Y/%m/')),
                ('is_public', models.BooleanField(default=False)),
                ('public_slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('header', 'Personal Header'), ('summary', 'Professional Summary'), ('experience', 'Work Experience'), ('education', 'Education'), ('skills', 'Skills'), ('projects', 'Projects'), ('certifications', 'Certifications'), ('languages', 'Languages'), ('awards', 'Awards & Honors'), ('references', 'References'), ('custom', 'Custom Section')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('data', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UploadedCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploaded_cvs/%Y/%m/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ats_score', models.IntegerField(blank=True, null=True)),
                ('vulnerability_report', models.JSONField(blank=True, default=dict)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('keyword_match', models.JSONField(blank=True, default=dict)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
            ],
        ),
    ]
